private
knownLabels
	
	^ #( 'Type-Bug' 'Type-FirstImpressionsCount' 'Type-Cleanup' 'Type-Enh' 'Type-FailingTest' 'Type-Feature' 'Type-HorribleErrorBlockingEverything'
	'Target-Collection' 'Target-Command' 'Target-Debugging' 'Target-File' 'Target-Fuel' 'Target-Jenkins' 'Target-Monticello' 'Target-Morphic' 'Target-NativeBoost' 'Target-Nautilus' 'Target-Network' 'Target-Opal' 'Target-Pharo' 'Target-RPackage' 'Target-Seed' 'Target-Spec' 'Target-Trait' 'Target-UI'
	'Milestone-1.0' 'Milestone-1.1' 'Milestone-1.2' 'Milestone-1.3' 'Milestone-1.4' 'Milestone-2.0' 'Milestone-3.0'
	'Importance-Low' 'Importance-High')