SystemOrganization addCategory: #'CI-Core'!
SystemOrganization addCategory: #'CI-Core-Extensions'!
SystemOrganization addCategory: #'CI-Core-Pharo'!
SystemOrganization addCategory: #'CI-Core-Publishing'!
SystemOrganization addCategory: #'CI-Core-SliceSubmitter'!
SystemOrganization addCategory: #'CI-Core-Source'!
SystemOrganization addCategory: #'CI-Core-Test'!
SystemOrganization addCategory: #'CI-Core-Validation'!
